### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by horseinthesky** [ds-voix/xswitcher#3]
Could you please describe how to configure `xswticher`?

I am looking at this file https://github.com/ds-voix/xswitcher/blob/main/gnome3/xswitcher.conf
and just don't quite understand what is going on there.

1) What are `WindowClasses`?
2) What does `Action`s do?
3) How to disable left Ctrl from switching the layout?
4) Is there a way to setup an Action to retype a selected block of text but not just last word?
5) F12 opens browsers debug. Is there a way to disable this? (I understand this is not quite `xswitcher` question but still)

**Comment by ds-voix** [comment]
[Here](https://habr.com/ru/post/499560/) You can find the explained config project.
The release was built upon this project. With only the few minor corrections. So, please open this aticle for more details.
The list below refers the article sections.
1. → §3. WindowClasses are about "Class of windows", as they are reported by X.
There names are reported after each focus switch when xswitcher is launched from console. The lines
`= telegram-desktop`: "telegram-desktop" is the class name.
You can rewrite full action set by setting `Actions = "AnotherActionsName"`. Of course, You also have to configure new section "[AnotherActionsName]".

2. → §4. "Action" triggers the hook, when the chain of the last keyboard events matches.

3. → §4. It is "Action.CyclicSwitch".
` "Action.CyclicSwitch" = [ "OFF:(R_CTRL|ALT|META|SHIFT)  SEQ:(L_CTRL:1,L_CTRL:0)" ] # Single short LEFT CONTROL
`
4. See https://github.com/ds-voix/xswitcher/issues/2#issuecomment-1026816806 §1

5. →  §4. Rewrite "[Actions]"-"Action.RetypeWord" expression in config.
```
 "Action.RetypeWord" = [ "OFF:(CTRL|ALT|META|SHIFT)  SEQ:(PAUSE:1,PAUSE:0)",
                         "OFF:(CTRL|ALT|META|SHIFT)  SEQ:(F12:1,F12:0)" ]

```
There is a set of comma-separated strings inside square brackets. Read the hint above "[Actions]" section inside the default config.

The short example. **"SEQ:(F12:1,F12:0)"**. Inside round brackets is placed the regex to be matched.
There is the simplest one: "F12:1" is "down" event for F12 key, then "F12:0" is "up" event for F12 key. This must be the latest events (therefore, implying "$" at the end of regex).
In the simplest case, one can just run `xswitcher -t` in the console, type whatever he/she wants and copy the output to the config…

**Comment by horseinthesky** [comment]
Ok so what I have now:
1) `WindowClasses` are basically speaking the active application name. So I can bind some hooks (`Actions`s) for `xswitcher` to do something immediately after I switch to this application window (correct me if I am wrong).
And you have something for `konsole`
```
[[WindowClasses]]
 Regex = "^konsole"
 # In general, mouse clicks leads to unpredictable (at the low-level where xswitcher resides) cursor jumps.
 # So, it's good choise to drop all buffers after click.
 # But some windows, e.g. terminals, can stay out of this problem.
 MouseClickDrops = false
 Actions = "Actions"
 ```
 a) I don't understand what does `drop all buffer` means in this case. So what are you NOT dropping for `konsole`?
 b) What does `Actions = "Actions"` do? What is default behavior?
 
 2) `Actions` are sort on mappings of
 a) `Action` - what to do
with
 b) Sequence of keys pressed?
 
 So here
 ```
  "Action.RetypeWord" = [ "OFF:(CTRL|ALT|META|SHIFT)  SEQ:(F12:1,F12:0)" ]
```
`RetypeWord` magic is hidden somewhere inside Go code and  ` OFF:(CTRL|ALT|META|SHIFT)  SEQ:(F12:1,F12:0)` means Ctrl/Alt/Meta/Shift are released and I press and release F12, rigth?!

But besided there keymappings there are also `WordChars`, `NewWord` and `NewSentence` in the same `Actions` block. They are not referenced anywhere. So how and why use them?

3) I just commented keymappings for a single Ctrl and L/R Shift press.

4) Still don't understand if it is possible to retype a block of selected text as Mirbi guy mentions in [his 2nd point](https://habr.com/ru/post/499560/#comment_21629386). Is is possible to do with the current state of the `xswitcher` or it need go coding?

5) Was able to disable F12 keymapping in Chrome with (extention)[https://chrome.google.com/webstore/detail/disable-f12/kpfnljnhmfhomajodmlepkcoflmbjiaf] =)

**Comment by ds-voix** [comment]
1. Yes, "konsole" is the console application from KDE. Generally, mouse doesn't affect the cursor in *nix consoles, so it's ok to not to invalidate buffers after detecting any mouse click.
In most or other cases (text editing windows), mouse click can move cursor to some unknown position. Xswitcher has no additional info, and must invalidate it's buffers after click detection.

As for `Actions = "Actions"`, 
`Actions =` points to the `[Section]` below. In this example, "Section" name is in fact "Actions". But it could be any, and up to one distinct section per each "WindowClasses".

2. Yes, "Actions" maps key sequence detector to "what to do when matched".
There are a bit of hardcoded actions ("Switch", "Layout", "RetypeWord", "Respawn", "Exec"). They can be chained one-by-one. Also, "Exec" can take the current input buffer, thus run away the logic from xswitcher blob.

Note that WordChars, NewWord and NewSentence are documented inside the config (even the embedded one).
E.g.
```
 # Count only those chars in word which must be removed (by sending the same count of BS keys) while "RetypeWord".
 WordChars = "(^@WORD@:0$)"

```
Also note that "@WORD@" is the macro defined above in the same config, the "[Templates]" section.
Templates were implemented because the plain regex becames human-unparsable during the modelling process.

3. It's completely ok to comment|delete any "unlinked" object from the config.

4. No. Xswitcher knows nothing about any "selection". It can trigger some external action by hotkey, no more.

5. May be. In any case, "functional" keys are the less preferred way to trigger actions inside the text editor. The ideal way is to find the key(s) with no "side effects". Like "pause" or "scroll lock" in "wide" keyboards.

**Comment by horseinthesky** [comment]
Ok. I more or less got what I am able to do with it =)
Switching a wrong layout of a currently typing word is already a big deal when you have to type fast on two layouts. Thanks again for the tool!

**Comment by aden16rus** [comment]
sorry for resurrect this issue, i just didn't find a way to set up action with combination of keys like super+space

**Comment by ds-voix** [comment]
Try this (rewrite the line in "[Actions]" section):
` "Action.CyclicSwitch" = [ "OFF:(CTRL|ALT|SHIFT) ON:(META)  SEQ:(SPACE:[12],SPACE:0)" ] # "super+space"
`
- Note that "space" will be typed. XSwitcher doesn't intercept the input. IBus intercepts, it provides a better way to "be like macos".
_Of course, there's a way to drop space via sending "BS". But this will be a kind of hack._
